# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Vault' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vault
  
  # source 'https://github.com/AudioKit/Specs.git'
  source 'https://github.com/CocoaPods/Specs.git'
  
  pod 'Alamofire', '~> 5'
  pod 'AlamofireImage', '~> 4'
  pod 'NVActivityIndicatorView'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'ObjectMapper', '~> 4.4.2'
  pod 'Parchment', '~> 3.2'
  pod 'SwiftMessages', '~> 7.0.0'
  pod 'QRCodeReader.swift', '~> 10.1.0'
  pod 'SideMenu'
  pod 'GVRSDK'

  target 'VaultTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VaultUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
  # Fix CocoaPods script phases that use realpath (not on older macOS) so errors are visible
  Dir[File.join(installer.sandbox.root, 'Target Support Files', '**', '*.sh')].each do |path|
    content = File.read(path)
    next unless content.include?('realpath')
    File.write(path, content.gsub('$(realpath -mq "${0}")', '"${0}"'))
  end
end
